name: ML Pipeline CI/CD

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-2  
  SAGEMAKER_ROLE: ${{ secrets.SAGEMAKER_ROLE }}
  MODEL_BUCKET: ${{ secrets.MODEL_BUCKET }}
  CONTAINER_IMAGE: ${{ secrets.CONTAINER_IMAGE }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pip install -e .  # Install package in development mode
          
      - name: Create directories
        run: |
          mkdir -p data
          mkdir -p logs
          mkdir -p test_features
          mkdir -p test_models
          
      - name: Setup test data
        run: python setup_test_data.py
          
      - name: Run tests
        run: |
          pytest tests/test_pipelines.py -v
          pytest tests/test_logging.py -v
          pytest tests/deep_test.py -v

  train:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          
      - name: Create directories
        run: |
          mkdir -p data
          mkdir -p logs
          
      - name: Setup data
        run: python setup_test_data.py
          
      - name: Process features
        run: python scripts/process_features.py
        
      - name: Train model
        run: python scripts/train_model.py

  evaluate:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Create directories
        run: |
          mkdir -p data
          mkdir -p logs
      - name: Setup data
        run: python setup_test_data.py
      - name: Process features
        run: python scripts/process_features.py
      - name: Evaluate Model
        run: python scripts/evaluate_model.py
      - name: Upload metrics
        uses: actions/upload-artifact@v2
        with:
          name: metrics
          path: metrics.json

  deploy:
    needs: evaluate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          
      - name: Download metrics
        uses: actions/download-artifact@v2
        with:
          name: metrics
          
      - name: Deploy to SageMaker
        run: python scripts/deploy_model.py